# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "News & Events"
    url = "/news/"
    weight = 1
[[main]]
    name = "Learn"
    url = "/learn/"
    weight = 2
[[main]]
    name = "Teach"
    url = "/teach/"
    weight = 3
[[main]]
    name = "Partner"
    url = "/partner/"
    weight = 4
[[main]]
    name = "Community"
    url = "https://community.rstudio.com/"
    weight = 5
