baseurl = "/"
theme = "rstudio-lithium"
relativeurls = false
languageCode = "en-us"
title = "Education"
description = "An opinionated collection of R packages designed for data science."
#googleAnalytics = "UA-115082821-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
# important! Do not use the below option
#disableKinds = ["taxonomyTerm"]

[permalinks]
  articles = "articles/:year/:month/:slug/"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]
